#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/exynos9610-common

PRODUCT_COPY_FILES += \
    vendor/motorola/exynos9610-common/proprietary/product/etc/permissions/com.motorola.camera2.content.ai.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.camera2.content.ai.xml \
    vendor/motorola/exynos9610-common/proprietary/product/etc/permissions/com.motorola.camera2.hallasan.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.camera2.hallasan.xml \
    vendor/motorola/exynos9610-common/proprietary/product/etc/permissions/deviceowner-configuration-com.motorola.camera2.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/deviceowner-configuration-com.motorola.camera2.xml \
    vendor/motorola/exynos9610-common/proprietary/product/etc/permissions/privapp-permissions-com.motorola.camera2.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.motorola.camera2.xml \
    vendor/motorola/exynos9610-common/proprietary/product/etc/sysconfig/hiddenapi-whitelist-com.motorola.camera2.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/hiddenapi-whitelist-com.motorola.camera2.xml \
    vendor/motorola/exynos9610-common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/motorola/exynos9610-common/proprietary/vendor/app/mcRegistry/00060308060501020000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/motorola/exynos9610-common/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/motorola/exynos9610-common/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/motorola/exynos9610-common/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/motorola/exynos9610-common/proprietary/vendor/app/mcRegistry/09090000070100010000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/09090000070100010000000000000000.tlbin \
    vendor/motorola/exynos9610-common/proprietary/vendor/app/mcRegistry/FFFFFFFFD00000000000000000000016.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/FFFFFFFFD00000000000000000000016.tlbin \
    vendor/motorola/exynos9610-common/proprietary/vendor/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    vendor/motorola/exynos9610-common/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/ap_gain_mmul.bin:$(TARGET_COPY_OUT_VENDOR)/etc/ap_gain_mmul.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/gnss/ca.pem:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/ca.pem \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-rbs.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-rbs.rc \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-uicc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-uicc-service.rc \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/init/samsung.hardware.media.c2@1.1-default-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/samsung.hardware.media.c2@1.1-default-service.rc \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/permissions/com.motorola.motosignature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.motorola.motosignature.xml \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/sec_s3nrn82_rfreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sec_s3nrn82_rfreg.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/sim_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sim_configuration.xml \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/bluetooth/bt.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/bluetooth/bt.hcf \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/bluetooth/platform.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/bluetooth/platform.txt \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/wlan/platform.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/wlan/platform.txt \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/wlan/wlan.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/wlan/wlan.hcf \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/wlan/wlan_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/wlan/wlan_sw.hcf \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/wlan/wlan_t.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/wlan/wlan_t.hcf \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/wlan/wlan_t_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_robusta2_dualfem/wlan/wlan_t_sw.hcf \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_troika_dualfem/bluetooth/bt.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_troika_dualfem/bluetooth/bt.hcf \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_troika_dualfem/bluetooth/platform.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_troika_dualfem/bluetooth/platform.txt \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_troika_dualfem/wlan/platform.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_troika_dualfem/wlan/platform.txt \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_troika_dualfem/wlan/wlan.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_troika_dualfem/wlan/wlan.hcf \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_troika_dualfem/wlan/wlan_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_troika_dualfem/wlan/wlan_sw.hcf \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_troika_dualfem/wlan/wlan_t.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_troika_dualfem/wlan/wlan_t.hcf \
    vendor/motorola/exynos9610-common/proprietary/vendor/etc/wifi/mx140/conf/leman_s620_troika_dualfem/wlan/wlan_t_sw.hcf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/mx140/conf/leman_s620_troika_dualfem/wlan/wlan_t_sw.hcf \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/AP_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/AP_AUDIO_SLSI.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/CC_DRAM_CODE_FLASH_HIFI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/CC_DRAM_CODE_FLASH_HIFI.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/CC_DTCM_CODE_FLASH_HIFI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/CC_DTCM_CODE_FLASH_HIFI.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/CC_ITCM_CODE_FLASH_HIFI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/CC_ITCM_CODE_FLASH_HIFI.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/CP_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/CP_AUDIO_SLSI.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/WithLightFixNoBN.SDNNmodel:$(TARGET_COPY_OUT_VENDOR)/firmware/WithLightFixNoBN.SDNNmodel \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_haptic.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Attentive.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Attentive.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Bird_Loop.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Bird_Loop.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Crazy_Dream.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Crazy_Dream.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Curve_Ball_Blend.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Curve_Ball_Blend.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Ether_Shake.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Ether_Shake.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Hello.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Hello.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Momentum.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Momentum.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Moto.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Moto.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Natural.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Natural.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Pyxis.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Pyxis.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Simple.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Simple.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/aw8695_rtp_Sparse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8695_rtp_Sparse.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/bl.unchecked.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bl.unchecked.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/bu24218_Rev1.5_S_data1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24218_Rev1.5_S_data1.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/bu24218_Rev1.5_S_data2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24218_Rev1.5_S_data2.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/bu24218_cal_data_default.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24218_cal_data_default.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/calliope_sram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_sram.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-aac-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-aac-cali.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-diag.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-diag.wmfw \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-prot.wmfw \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-qissheng-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-qissheng-cali.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-indmusic-aac.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-indmusic-aac.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-indmusic-qisheng.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-indmusic-qisheng.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-music-aac.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-music-aac.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-music-qisheng.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-music-qisheng.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-notification-aac.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-notification-aac.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-notification-qisheng.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-notification-qisheng.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-ringtone-aac.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-ringtone-aac.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-ringtone-qisheng.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-ringtone-qisheng.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-voice-aac.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-voice-aac.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-voice-qisheng.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-voice-qisheng.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/default_configuration.hfd.cfg.json:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.hfd.cfg.json \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/marley-dsp2-aov-frontend.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp2-aov-frontend.wmfw \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/marley-dsp2-aov-vrgain.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp2-aov-vrgain.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/marley-dsp3-aov-control.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp3-aov-control.wmfw \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/pp_cfg.json:$(TARGET_COPY_OUT_VENDOR)/firmware/pp_cfg.json \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/sec_s3nrn81_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3nrn81_firmware.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/sec_s3nrn82_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3nrn82_firmware.bin \
    vendor/motorola/exynos9610-common/proprietary/vendor/firmware/tracker_cfg.json:$(TARGET_COPY_OUT_VENDOR)/firmware/tracker_cfg.json

PRODUCT_PACKAGES += \
    libmediaadaptor \
    libGLES_mali \
    keystore.exynos9610 \
    power.exynos9610 \
    thermal.exynos9610 \
    vendor.egistec.hardware.fingerprint@4.0-impl \
    libENF \
    libdapparamstorage \
    libexynoscamera_hifi_plugin \
    libexynoscamera_hifills_plugin \
    libexynoscamera_plugin \
    libexynoscamera_plugin_utils \
    libexynoscamera_vdis_plugin \
    libhifills \
    libhubconnection \
    libril_sitril \
    libsitril-audio \
    libsitril-client \
    libsitril-gps \
    libsitril-ims \
    libsitril-nr \
    libsitril-psensor \
    libsitril-sar \
    libsitril-se \
    libsitril-wlan \
    libsitril \
    libvdis \
    libyuvrepro \
    sensors.rp \
    vendor.egistec.hardware.fingerprint@4.0 \
    vendor.samsung_slsi.telephony.hardware.oemservice@1.0 \
    vendor.samsung_slsi.telephony.hardware.radio@1.0 \
    vendor.samsung_slsi.telephony.hardware.radio@1.1 \
    vendor.samsung_slsi.telephony.hardware.radioExternal@1.0 \
    vendor.samsung_slsi.telephony.hardware.radioExternal@1.1 \
    audio.primary.exynos9610 \
    libalsautils_sec \
    libaudio-ril \
    libaudioproxy \
    libmotaudioutils \
    liboemcrypto \
    libunshorten \
    libwvhidl \
    android.hardware.gnss@1.0-impl.samsung \
    android.hardware.gnss@1.1-impl.samsung \
    android.hardware.gnss@2.0-impl.samsung \
    vendor.samsung.hardware.gnss@1.0-impl \
    libRbsFlow \
    libadropbox \
    libcharon \
    libstrongswan \
    MotoSignatureApp \
    ShannonIms \
    OemRilService \
    MotCamera2AI \
    HotwordEnrollmentOKGoogleWM8280 \
    HotwordEnrollmentXGoogleWM8280 \
    MotCamera2 \
    ShannonDataService \
    ShannonNetworkService \
    ShannonQualifiedNetworksService \
    com.motorola.motosignature \
    com.android.hotwordenrollment.common.util \
    cbd \
    charge_only_mode \
    charon \
    exynos-thermald \
    android.hardware.biometrics.fingerprint@2.1-service-rbs \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.secure_element@1.2-uicc-service \
    gpsd \
    rild_exynos \
    samsung.hardware.media.c2@1.1-default-service \
    main_abox \
    wfc-pkt-router

PRODUCT_PACKAGES += \
    vendor_lib_hw_vulkan_exynos9610_so \
    vendor_lib_libOpenCL_so \
    vendor_lib_libOpenCL_so_1 \
    vendor_lib_libOpenCL_so_1_1 \
    vendor_lib64_hw_vulkan_exynos9610_so \
    vendor_lib64_libOpenCL_so \
    vendor_lib64_libOpenCL_so_1 \
    vendor_lib64_libOpenCL_so_1_1
